### ISSUE TITLE
python API: queries fail with "not well-formed (invalid token): line 121, column 69"

### ISSUE THREAD

**Issue by simonepigazzini** [cms-DQM/runregistry#12]
Since this morning even simple queries like: 

`run = runregistry.get_run(run_number=328762)`

fail with the ParseError reported in the subject of this issue

**Comment by pmandrik** [comment]
Failed due to authentication error:

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    oms_lumisections = runregistry.get_oms_lumisections(run, cert=(cert, key))
  File "/home/rr_test/runregistry/runregistry_api_client/runregistry/runregistry.py", line 256, in get_oms_lumisections
    return _get_lumisection_helper(url, run_number, dataset_name, **kwargs)
  File "/home/rr_test/runregistry/runregistry_api_client/runregistry/runregistry.py", line 233, in _get_lumisection_helper
    cookies = _get_cookies(url, **kwargs)
  File "/home/rr_test/runregistry/runregistry_api_client/runregistry/runregistry.py", line 44, in _get_cookies
    cookies = get_sso_cookies(url, cert, verify=False)
  File "/usr/local/lib/python3.6/site-packages/cernrequests/cookies.py", line 82, in get_sso_cookies
    action, form_data = _extract_login_form(authentication_response.content)
  File "/usr/local/lib/python3.6/site-packages/cernrequests/cookies.py", line 38, in _extract_login_form
    tree = ElementTree.fromstring(response_content)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 121, column 69
```

Related issue in cernrequests library:
https://github.com/CMSTrackerDPG/cernrequests/issues/2

**Comment by pmandrik** [comment]
Hi, @simonepigazzini , the issue seems to be fixed at CERN SSO service side and now authentication with cernrequests is working for me again. Could you please check?

**Comment by simonepigazzini** [comment]
Hi @pmandrik, yes! my system resumed operation about 1h ago. Thanks.
